import logoutAPi from './logout'
import getIndiAdmin from './superadmin/getIndiAdmin'
import getAllProfessors from './superadmin/getAllProfessors'
import getAllStaff from './superadmin/getAllStaffs'
import getAllProjects from './superadmin/getAllProjects'
import getAllUsers from './superadmin/getAllUsers'
import getIndiStaff from './staff/getIndiStaff'
import getIndiProfessor from './professor/getIndiProfessor'
import createPayrole from './staff/createPayroleStaff'
import getPayroleStaff from './staff/getPayroleStaff'
import getAllPayroles from './superadmin/getAllPayroles'
import getPayroleProfessor from './professor/getPayroleProfessor'
import updatePayrole from './professor/updatePayrole'
import updateStaff from './staff/updateStaff'
import updateProfessor from './professor/updateProfessor'   
import getIndiProject from './superadmin/getIndiProject'
import updateProject from './superadmin/updateProject'
export { logoutAPi, getIndiAdmin, getAllProfessors, getAllStaff, getAllProjects, getAllUsers, getIndiStaff, getIndiProfessor, createPayrole, getPayroleStaff, getPayroleProfessor, updatePayrole, getAllPayroles, updateStaff, updateProfessor, getIndiProject, updateProject }
